### ISSUE TITLE
Revisão e Criação de CDUs

### ISSUE THREAD

**Issue by jlucfarias** [josetvictor/buscabelo#1]
## Tarefas

 - [x] Revisar CDUs

### Novos CDUs

 - [x] Acessar HIstórico
 - [x] Avaliar Serviço

## Responsáveis
 - @josetvictor 
 - @lucashec

**Comment by lucashec** [comment]
### CDU - Avaliar Serviço 
*destaco aqui a necessiadade da modelagem da entidade estabelecimento, de forma que ela possa contemplar a possibiliade de execução de uma query do tipo: avg(notas, num_avaliadores). Outras sugestões usando tabela intermediárias também podem ser analisadas.*

**Comment by jlucfarias** [comment]
Não vejo necessidade para considerar execução de query para este caso, @lucashec. Se a tecnologia utilizada agora ou no futuro utiliza de ORMs (caso do Django), o cálculo dessas avaliações pode se dar sem problemas no backend da aplicação. De outra forma, seria bastante interessante resolver esse problema utilizando [Views SQL](https://www.devmedia.com.br/como-funcionam-as-views-no-postgresql/33808) que acarretariam em mais segurança e comodidade na hora de programar já que a lógica da consulta estaria toda no banco de dados e exclui a possibilidade de manipulação dos dados diretamente na view
