### ISSUE TITLE
Criação dos Protótipos de Tela

### ISSUE THREAD

**Issue by jlucfarias** [josetvictor/buscabelo#3]
## Tarefas
 - [x] Página Inicial
 - [x] Página do Estabelecimento
 - [x] Página de Login
 - [x] Página de Detalhamento do Serviço
 - [ ] Página de Agendamento

[Link](https://www.figma.com/file/a2XpugUUylNClnsOvqpDI4/Buscabelo?node-id=12%3A17) para os protótipos

## Responsável
- @jlucfarias

**Comment by jlucfarias** [comment]
## Protótipos criados antes da Pandemia

### Página Inicial

![Pré-Home](https://user-images.githubusercontent.com/15695983/102883666-23d14100-442f-11eb-8a74-a4947c804b03.png)

### Página de Produto

![Pré-Detalhamento do Serviço](https://user-images.githubusercontent.com/15695983/102883683-2b90e580-442f-11eb-8f71-762e4fb8c8b3.png)

_Para a época, servia exatamente como a página de detalhamento do serviço_

**Comment by jlucfarias** [comment]
Eu vou esperar a resolução de #1 para continuar nos protótipos devido à tela de agendamento

**Comment by josetvictor** [comment]
Boa @jlucfarias , tu tinha isso guardado, muito bom para no futuro a gente ver nossa visão das primeiras semanas de ideia, para a aplicação quando tiver mais avançada.
